name: Publish Release

on:
  push:
    # Trigger unless only the wiki directory changed
    paths-ignore:
      - "wiki/**"
      - "**/**.md"
    branches: [ "master" ]

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    environment: release
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update version
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Print output
        run: echo "Commitizen output ${{ steps.cz.outputs }}"

      - name: Run image
        if: steps.cz.outputs.version
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: '1.5.1'

      - name: Install dependencies
        if: steps.cz.outputs.version
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine

      - name: Update manifest.json version
        if: steps.cz.outputs.version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: custom_components/uk_bin_collection/manifest.json
          field: version
          value: ${{ steps.cz.outputs.version }}

      - name: Update manifest.json requirements
        if: steps.cz.outputs.version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: custom_components/uk_bin_collection/manifest.json
          field: requirements[0]
          value: uk-bin-collection>=${{ steps.cz.outputs.version }}

      - name: Install
        if: steps.cz.outputs.version
        run: make install

      - name: Create release
        if: steps.cz.outputs.version
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.cz.outputs.version }}
          generateReleaseNotes: true
          prerelease: true

      - name: Build and publish package
        if: steps.cz.outputs.version
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
          poetry publish --build
