name: Publish Release

on:
  push:
    # Trigger unless only the wiki directory changed
    paths-ignore:
      - "wiki/**"
      - "**/**.md"
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update version
        uses: commitizen-tools/commitizen-action@master
        with:
          push: false

      - name: Run image
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: '1.5.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine

      - name: Update manifest.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: custom_components/uk_bin_collection/manifest.json
          field: version
          value: ${{ env.REVISION }}

      - name: Update manifest.json requirements
        uses: jossef/action-set-json-field@v2.1
        with:
          file: custom_components/uk_bin_collection/manifest.json
          field: requirements[0]
          value: uk-bin-collection>=${{ env.REVISION }}

      - name: Install
        run: make install

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.REVISION }}
          generateReleaseNotes: true

      - name: Build and publish package
        if: steps.release.outputs.released
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
          poetry publish --build
